### ISSUE TITLE
Some Python dependencies must be installed twice in order to use the examples

### ISSUE THREAD

**Issue by ccooper21** [ramhiser/serverless-cloud-vision#3]
Since the Python dependencies for the AWS Lambda service are being installed into a special directory, `cloudvision/vendored`, such that they will get deployed by Serverless, they are not available for use by the included examples.  I found that I had to install both the `requests` and `Pillow` packages in order for the examples to be used, as follows:

`pip install requests Pillow`

**Comment by ramhiser** [comment]
@ccooper21 Good point. I glossed over that detail -- I'll add a note to the `README`.
